/*Get Utensils and Ingredients
    Get Teacup
    Get Spoon
    Get Tea Kettle
    Get Teapot
    Get Tea
    Get Sugar
Boil water in a Tea Kettle
    Fill Kettle with Water
    Switch Kettle On
    Wait for Kettle to Boil
Make Tea in Teapot
    Put Tea in Teapot
    Put Boiling Water in Teapot
    Wait 2 Minutes
Add Tea and Sugar to Teacup
    Pour Tea in Teacup
    Put 1 teaspoon of Sugar in Teacup
    Stir Tea in Teacup
Serve Tea to a Friend*/
public class Teatime {
}